graph TB
    node0[package.json]
    style node0 fill:#fdcb6e,stroke:#2d3436
    node1[init-database.js]
    style node1 fill:#fdcb6e,stroke:#2d3436
    node2[server.js]
    style node2 fill:#ff7675,stroke:#2d3436

    %% Key Dependencies
    node2 --> node0
    node2 --> node1
