/**
 * Email Templates Seeder
 * Seeds the email_templates table with default template.
 * Part of v1.0.21 Template Editor feature implementation.
 *
 * @module SeedEmailTemplates
 * @version 1.0.21
 */

/**
 * Default email template content with variable placeholders
 */
const defaultTemplate = `Subject: Hexagon Work Order - [SITE_NAME] - [HEXAGON_NUM]

Hello [GREETING],

We have submitted a Hexagon work order ([HEXAGON_NUM]) for the [SITE_NAME] site.

There are critical security patches that must be applied within 30 days.

Please see the attached notes for more information. If you have any questions or concerns please feel free to reach out to NetOps at netops@oneok.com.

**MAINTENANCE DETAILS:**
• Location: [SITE_NAME] - [LOCATION]
• Hexagon Ticket: [HEXAGON_NUM]
• ServiceNow Reference: [SERVICENOW_NUM]
• Required Completion: [DATE_DUE]

**AFFECTED SYSTEMS:**
[DEVICE_COUNT] device[DEVICE_COUNT > 1 ? 's' : ''] require security patches and will need to be rebooted:
[DEVICE_LIST]

**ACTION REQUIRED:**
• Schedule a maintenance window of at least 2 hours
• Contact ITCC at 918-732-4822 with ServiceNow ticket [SERVICENOW_NUM]
• Coordinate with NetOps for patch application

**TIMELINE:**
• Request Submitted: [DATE_SUBMITTED]
• Required Completion: [DATE_DUE]
• Maintenance Window: To be scheduled

[VULNERABILITY_SUMMARY]

Please confirm receipt and provide your proposed maintenance window.

---
Generated by HexTrackr v1.0.21
Ticket ID: [XT_NUMBER]`;

/**
 * Available variables for the email template
 */
const templateVariables = [
    {
        name: "[GREETING]",
        description: "Supervisor first name or 'Team' for multiple supervisors",
        required: false,
        fallback: "[Supervisor First Name]"
    },
    {
        name: "[SITE_NAME]",
        description: "Site name from ticket",
        required: true,
        fallback: "[Site Name]"
    },
    {
        name: "[LOCATION]",
        description: "Location from ticket",
        required: true,
        fallback: "[Location]"
    },
    {
        name: "[HEXAGON_NUM]",
        description: "Hexagon ticket number",
        required: false,
        fallback: "[Hexagon #]"
    },
    {
        name: "[SERVICENOW_NUM]",
        description: "ServiceNow ticket number",
        required: false,
        fallback: "[ServiceNow #]"
    },
    {
        name: "[XT_NUMBER]",
        description: "Internal XT number",
        required: true,
        fallback: "XT#[ID]"
    },
    {
        name: "[DEVICE_COUNT]",
        description: "Number of devices in ticket",
        required: true,
        fallback: "0"
    },
    {
        name: "[DEVICE_LIST]",
        description: "Enumerated list of devices",
        required: true,
        fallback: "Device list to be confirmed"
    },
    {
        name: "[DATE_DUE]",
        description: "Due date formatted",
        required: true,
        fallback: "[Due Date]"
    },
    {
        name: "[DATE_SUBMITTED]",
        description: "Submission date formatted",
        required: true,
        fallback: "[Submitted Date]"
    },
    {
        name: "[VULNERABILITY_SUMMARY]",
        description: "Dynamic vulnerability summary (generated at runtime)",
        required: false,
        fallback: ""
    }
];

/**
 * Seed email templates into database
 * @param {sqlite3.Database} db - Database connection
 * @returns {Promise<void>}
 */
async function seedEmailTemplates(db) {
    return new Promise((resolve, reject) => {
        // Check if template already exists
        db.get(
            "SELECT id FROM email_templates WHERE name = ?",
            ["default_email"],
            (err, row) => {
                if (err) {
                    return reject(new Error("Failed to check existing templates: " + err.message));
                }

                if (row) {
                    console.log("✅ Default email template already exists");
                    return resolve();
                }

                // Insert default template
                const insertSql = `
                    INSERT INTO email_templates (
                        name,
                        description,
                        template_content,
                        default_content,
                        variables,
                        category,
                        is_active
                    ) VALUES (?, ?, ?, ?, ?, ?, ?)
                `;

                const params = [
                    "default_email",
                    "Default email template for supervisor notifications",
                    defaultTemplate,
                    defaultTemplate,
                    JSON.stringify(templateVariables),
                    "ticket",
                    1
                ];

                db.run(insertSql, params, function(insertErr) {
                    if (insertErr) {
                        return reject(new Error("Failed to insert default template: " + insertErr.message));
                    }

                    console.log(`✅ Default email template seeded with ID: ${this.lastID}`);
                    resolve();
                });
            }
        );
    });
}

/**
 * Reset email template to default
 * @param {sqlite3.Database} db - Database connection
 * @param {string} templateName - Template name to reset
 * @returns {Promise<void>}
 */
async function resetTemplateToDefault(db, templateName = "default_email") {
    return new Promise((resolve, reject) => {
        const updateSql = `
            UPDATE email_templates
            SET template_content = default_content,
                updated_at = CURRENT_TIMESTAMP
            WHERE name = ?
        `;

        db.run(updateSql, [templateName], function(err) {
            if (err) {
                return reject(new Error("Failed to reset template: " + err.message));
            }

            if (this.changes === 0) {
                console.log("⚠️ No template found to reset");
            } else {
                console.log(`✅ Template '${templateName}' reset to default`);
            }

            resolve();
        });
    });
}

module.exports = {
    seedEmailTemplates,
    resetTemplateToDefault,
    defaultTemplate,
    templateVariables
};