/**
 * Template Seeder Utilities
 * Seeds email, ticket, and vulnerability template tables with defaults.
 * Part of v1.0.21 Template Editor feature implementation.
 *
 * @module SeedTemplates
 * @version 1.0.21
 */

/**
 * Default template definitions
 */
const defaultEmailTemplate = `Subject: Hexagon Work Order - [SITE_NAME] - [HEXAGON_NUM]

Hello [GREETING],

We have submitted a Hexagon work order ([HEXAGON_NUM]) for the [SITE_NAME] site.

There are critical security patches that must be applied within 30 days.

Please see the attached notes for more information. If you have any questions or concerns please feel free to reach out to NetOps at netops@oneok.com.

**MAINTENANCE DETAILS:**
• Location: [SITE_NAME] - [LOCATION]
• Hexagon Ticket: [HEXAGON_NUM]
• ServiceNow Reference: [SERVICENOW_NUM]
• Required Completion: [DATE_DUE]

**AFFECTED SYSTEMS:**
[DEVICE_COUNT] device(s) require security patches and will need to be rebooted:
[DEVICE_LIST]

**ACTION REQUIRED:**
• Schedule a maintenance window of at least 2 hours
• Contact ITCC at 918-732-4822 with ServiceNow ticket [SERVICENOW_NUM]
• Coordinate with NetOps for patch application

**TIMELINE:**
• Request Submitted: [DATE_SUBMITTED]
• Required Completion: [DATE_DUE]
• Maintenance Window: To be scheduled

[VULNERABILITY_SUMMARY]

Please confirm receipt and provide your proposed maintenance window.

---
Generated by HexTrackr v1.0.21
Ticket ID: [XT_NUMBER]`;

const emailTemplateVariables = [
    { name: "[GREETING]", description: "Supervisor first name or 'Team'", required: false, fallback: "[Supervisor First Name]" },
    { name: "[SITE_NAME]", description: "Site name from ticket", required: true, fallback: "[Site Name]" },
    { name: "[LOCATION]", description: "Location from ticket", required: true, fallback: "[Location]" },
    { name: "[HEXAGON_NUM]", description: "Hexagon ticket number", required: false, fallback: "[Hexagon #]" },
    { name: "[SERVICENOW_NUM]", description: "ServiceNow ticket number", required: false, fallback: "[ServiceNow #]" },
    { name: "[XT_NUMBER]", description: "Internal XT number", required: true, fallback: "XT#[ID]" },
    { name: "[DEVICE_COUNT]", description: "Number of devices", required: true, fallback: "0" },
    { name: "[DEVICE_LIST]", description: "Enumerated device list", required: true, fallback: "Device list to be confirmed" },
    { name: "[DATE_DUE]", description: "Due date formatted", required: true, fallback: "[Due Date]" },
    { name: "[DATE_SUBMITTED]", description: "Submission date formatted", required: true, fallback: "[Submitted Date]" },
    { name: "[VULNERABILITY_SUMMARY]", description: "Runtime vulnerability summary", required: false, fallback: "" }
];

const defaultTicketTemplate = `# Hexagon Work Request

**Ticket Information:**
- Hexagon Ticket #: [HEXAGON_TICKET]
- ServiceNow Ticket #: [SERVICENOW_TICKET]
- XT Number: [XT_NUMBER]
- Site: [SITE_NAME]
- Location: [LOCATION]
- Status: [STATUS]

**Timeline:**
- Date Submitted: [DATE_SUBMITTED]
- Required Completion Date: [DATE_DUE]

**Task Instruction:**
There are critical security patches that must be applied within 30 days at the [SITE_NAME] site. Please schedule a maintenance outage of at least two hours and contact the ITCC at 918-732-4822 with ServiceNow ticket [SERVICENOW_TICKET] to coordinate NetOps for applying security updates and rebooting the equipment.

**Devices to be Updated:**
The following [DEVICE_COUNT] device(s) will be updated and rebooted:

[DEVICE_LIST]

**Personnel:**
- Supervisor: [SUPERVISOR]
- Technician: [TECHNICIAN]

**Additional Notes:**
[NOTES]

---
Generated: [GENERATED_TIME]`;

const ticketTemplateVariables = [
    { name: "[HEXAGON_TICKET]", description: "Hexagon ticket number", required: false, fallback: "[Hexagon Ticket]" },
    { name: "[SERVICENOW_TICKET]", description: "ServiceNow ticket number", required: false, fallback: "[ServiceNow Ticket]" },
    { name: "[XT_NUMBER]", description: "Internal XT number", required: true, fallback: "XT#[ID]" },
    { name: "[SITE_NAME]", description: "Site name", required: true, fallback: "[Site]" },
    { name: "[LOCATION]", description: "Location name", required: true, fallback: "[Location]" },
    { name: "[STATUS]", description: "Ticket status", required: true, fallback: "[Status]" },
    { name: "[DATE_SUBMITTED]", description: "Submission date", required: true, fallback: "[Date Submitted]" },
    { name: "[DATE_DUE]", description: "Due date", required: true, fallback: "[Due Date]" },
    { name: "[DEVICE_LIST]", description: "Formatted device list", required: true, fallback: "Device list to be confirmed" },
    { name: "[DEVICE_COUNT]", description: "Device count", required: true, fallback: "0" },
    { name: "[SUPERVISOR]", description: "Supervisor name", required: false, fallback: "[Supervisor]" },
    { name: "[TECHNICIAN]", description: "Technician name", required: false, fallback: "[Technician]" },
    { name: "[NOTES]", description: "Additional notes", required: false, fallback: "N/A" },
    { name: "[GENERATED_TIME]", description: "Generation timestamp", required: false, fallback: "[Generated Timestamp]" },
    { name: "[GREETING]", description: "Supervisor greeting", required: false, fallback: "Team" },
    { name: "[VULNERABILITY_SUMMARY]", description: "Vulnerability summary section", required: false, fallback: "" }
];

const defaultVulnerabilityTemplate = `# Vulnerability Report for [LOCATION]

**XT#:** [XT_NUMBER]
**Hexagon#:** [HEXAGON_TICKET]
**ServiceNow#:** [SERVICENOW_TICKET]

Generated: [GENERATED_TIME]

## Summary

**Total Vulnerabilities:** [TOTAL_VULNERABILITIES]
- **Critical:** [CRITICAL_COUNT]
- **High:** [HIGH_COUNT]
- **Medium:** [MEDIUM_COUNT]
- **Low:** [LOW_COUNT]

**Devices Affected:** [DEVICE_COUNT]

## Vulnerability Details

[VULNERABILITY_DETAILS]

---

**Report End**

*This report was generated automatically from vulnerability scan data. Please review all findings and coordinate with the security team for remediation planning.*`;

const vulnerabilityTemplateVariables = [
    { name: "[LOCATION]", description: "Location or site name", required: true, fallback: "[Location]" },
    { name: "[XT_NUMBER]", description: "Internal XT number", required: true, fallback: "XT#[ID]" },
    { name: "[HEXAGON_TICKET]", description: "Hexagon ticket number", required: false, fallback: "[Hexagon Ticket]" },
    { name: "[SERVICENOW_TICKET]", description: "ServiceNow ticket number", required: false, fallback: "[ServiceNow Ticket]" },
    { name: "[GENERATED_TIME]", description: "Report timestamp", required: false, fallback: "[Generated Timestamp]" },
    { name: "[VULNERABILITY_DETAILS]", description: "Per-device vulnerability details", required: true, fallback: "No vulnerability data available." },
    { name: "[TOTAL_VULNERABILITIES]", description: "Total vulnerability count", required: false, fallback: "0" },
    { name: "[CRITICAL_COUNT]", description: "Critical vulnerability count", required: false, fallback: "0" },
    { name: "[HIGH_COUNT]", description: "High vulnerability count", required: false, fallback: "0" },
    { name: "[MEDIUM_COUNT]", description: "Medium vulnerability count", required: false, fallback: "0" },
    { name: "[LOW_COUNT]", description: "Low vulnerability count", required: false, fallback: "0" },
    { name: "[DEVICE_COUNT]", description: "Devices with vulnerabilities", required: false, fallback: "0" }
];

/**
 * Seed email templates into database
 * @param {sqlite3.Database} db - Database connection
 * @returns {Promise<void>}
 */
const templateSignatures = {
    email: ['Subject: Hexagon Work Order', '[DEVICE_LIST]'],
    ticket: ['# Hexagon Work Request', 'Generated:'],
    vulnerability: ['# Vulnerability Report', '[VULNERABILITY_DETAILS]', '[TOTAL_VULNERABILITIES]']
};

function contentLooksMismatched(content, category) {
    if (!content) {
        return true;
    }

    const normalizedCategory = (category || '').toLowerCase();
    const expectedTokens = templateSignatures[normalizedCategory] || [];
    const foreignTokens = Object.entries(templateSignatures)
        .filter(([key]) => key !== normalizedCategory)
        .flatMap(([, tokens]) => tokens);

    const containsExpected = expectedTokens.some(token => content.includes(token));
    const containsForeign = foreignTokens.some(token => content.includes(token));

    if (containsForeign) {
        return true;
    }

    if (!containsExpected) {
        return content.trim().length === 0;
    }

    return false;
}

async function seedTemplate(db, { table, name, description, defaultContent, variables, category }) {
    return new Promise((resolve, reject) => {
        db.get(
            `SELECT id, template_content, default_content, category FROM ${table} WHERE name = ?`,
            [name],
            (err, row) => {
                if (err) {
                    return reject(new Error(`Failed to check existing ${table} templates: ${err.message}`));
                }

                if (row) {
                    const storedCategory = (row.category || '').toLowerCase();
                    const needsRepair = storedCategory !== category
                        || contentLooksMismatched(row.template_content, category)
                        || contentLooksMismatched(row.default_content, category);

                    if (!needsRepair) {
                        console.log(`✅ Template '${name}' already exists in ${table}`);
                        return resolve();
                    }

                    const repairSql = `
                        UPDATE ${table}
                           SET template_content = ?,
                               default_content = ?,
                               category = ?,
                               updated_at = CURRENT_TIMESTAMP
                         WHERE id = ?
                    `;

                    db.run(
                        repairSql,
                        [
                            defaultContent,
                            defaultContent,
                            category,
                            row.id
                        ],
                        function(updateErr) {
                            if (updateErr) {
                                return reject(new Error(`Failed to repair template '${name}': ${updateErr.message}`));
                            }

                            console.log(`🔄 Repaired template '${name}' in ${table} to restore default content`);
                            resolve();
                        }
                    );
                    return;
                }

                const insertSql = `
                    INSERT INTO ${table} (
                        name,
                        description,
                        template_content,
                        default_content,
                        variables,
                        category,
                        is_active
                    ) VALUES (?, ?, ?, ?, ?, ?, 1)
                `;

                db.run(
                    insertSql,
                    [
                        name,
                        description,
                        defaultContent,
                        defaultContent,
                        JSON.stringify(variables),
                        category,
                        1
                    ],
                    function(insertErr) {
                        if (insertErr) {
                            return reject(new Error(`Failed to insert template '${name}': ${insertErr.message}`));
                        }

                        console.log(`✅ Seeded template '${name}' (ID: ${this.lastID}) in ${table}`);
                        resolve();
                    }
                );
            }
        );
    });
}

async function seedEmailTemplates(db) {
    await seedTemplate(db, {
        table: 'email_templates',
        name: 'default_email',
        description: 'Default email template for supervisor notifications',
        defaultContent: defaultEmailTemplate,
        variables: emailTemplateVariables,
        category: 'email'
    });
}

async function seedTicketTemplates(db) {
    await seedTemplate(db, {
        table: 'ticket_templates',
        name: 'default_ticket',
        description: 'Default ticket markdown template',
        defaultContent: defaultTicketTemplate,
        variables: ticketTemplateVariables,
        category: 'ticket'
    });
}

async function seedVulnerabilityTemplates(db) {
    await seedTemplate(db, {
        table: 'vulnerability_templates',
        name: 'default_vulnerability',
        description: 'Default vulnerability report template',
        defaultContent: defaultVulnerabilityTemplate,
        variables: vulnerabilityTemplateVariables,
        category: 'vulnerability'
    });
}

async function seedAllTemplates(db) {
    await seedEmailTemplates(db);
    await seedTicketTemplates(db);
    await seedVulnerabilityTemplates(db);
}

/**
 * Reset email template to default
 * @param {sqlite3.Database} db - Database connection
 * @param {string} templateName - Template name to reset
 * @returns {Promise<void>}
 */
async function resetTemplateToDefault(db, templateName = "default_email") {
    return new Promise((resolve, reject) => {
        const updateSql = `
            UPDATE email_templates
            SET template_content = default_content,
                updated_at = CURRENT_TIMESTAMP
            WHERE name = ?
        `;

        db.run(updateSql, [templateName], function(err) {
            if (err) {
                return reject(new Error("Failed to reset template: " + err.message));
            }

            if (this.changes === 0) {
                console.log("⚠️ No template found to reset");
            } else {
                console.log(`✅ Template '${templateName}' reset to default`);
            }

            resolve();
        });
    });
}

module.exports = {
    seedEmailTemplates,
    seedTicketTemplates,
    seedVulnerabilityTemplates,
    seedAllTemplates,
    resetTemplateToDefault,
    defaultEmailTemplate,
    emailTemplateVariables,
    defaultTicketTemplate,
    ticketTemplateVariables,
    defaultVulnerabilityTemplate,
    vulnerabilityTemplateVariables,
    contentLooksMismatched
};
