-- Migration 012: Create Audit Logs Infrastructure
-- Date: 2025-10-16
-- Issue: HEX-254
-- Description: Encrypted audit trail with 30-day retention for compliance and security monitoring

-- ============================================================================
-- Table: audit_logs
-- Purpose: Store encrypted audit trail for security-critical operations
-- Encryption: AES-256-GCM (data + metadata encrypted, category + timestamp indexed)
-- Retention: 30 days by default (configurable in logging.config.json)
-- ============================================================================

CREATE TABLE IF NOT EXISTS audit_logs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,

    -- Event Classification (indexed for fast queries)
    category TEXT NOT NULL,                    -- e.g., 'user.login', 'ticket.delete', 'import.start'
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,

    -- User Context (may be NULL for system events)
    user_id TEXT,                              -- User identifier (if authenticated)
    username TEXT,                             -- Username for quick lookup

    -- Request Context (if web request)
    ip_address TEXT,                           -- Client IP address
    user_agent TEXT,                           -- Browser/client identifier
    request_id TEXT,                           -- Correlation ID from request logging

    -- Encrypted Payload (contains sensitive details)
    encrypted_message BLOB NOT NULL,           -- AES-256-GCM encrypted message
    encrypted_data BLOB,                       -- AES-256-GCM encrypted JSON data object
    encryption_iv BLOB NOT NULL,               -- Initialization vector for decryption

    -- Metadata
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_audit_logs_category ON audit_logs(category);
CREATE INDEX IF NOT EXISTS idx_audit_logs_timestamp ON audit_logs(timestamp);
CREATE INDEX IF NOT EXISTS idx_audit_logs_user_id ON audit_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_username ON audit_logs(username);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON audit_logs(created_at);

-- Composite index for common query pattern (category + time range)
CREATE INDEX IF NOT EXISTS idx_audit_logs_category_timestamp ON audit_logs(category, timestamp);

-- ============================================================================
-- Table: audit_log_config
-- Purpose: Store encryption key and audit configuration metadata
-- Security: Key should be rotated periodically (future enhancement)
-- ============================================================================

CREATE TABLE IF NOT EXISTS audit_log_config (
    id INTEGER PRIMARY KEY CHECK (id = 1),     -- Singleton table (only 1 row allowed)

    -- Encryption Key (generated on first initialization)
    encryption_key BLOB NOT NULL,              -- AES-256 key (32 bytes)
    key_created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    key_rotated_at DATETIME,                   -- For future key rotation feature

    -- Retention Policy
    retention_days INTEGER DEFAULT 30,         -- Days to keep audit logs
    last_cleanup_at DATETIME,                  -- Last purge timestamp

    -- Statistics
    total_logs_written INTEGER DEFAULT 0,      -- Lifetime audit log count
    total_logs_purged INTEGER DEFAULT 0,       -- Lifetime purge count

    -- Metadata
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Initialize config table with defaults (if not exists)
-- Note: encryption_key will be generated by LoggingService on first init
INSERT OR IGNORE INTO audit_log_config (id, retention_days)
VALUES (1, 30);

-- ============================================================================
-- Migration Verification
-- ============================================================================

-- Verify tables exist
SELECT
    'audit_logs' as table_name,
    COUNT(*) as row_count
FROM audit_logs
UNION ALL
SELECT
    'audit_log_config' as table_name,
    COUNT(*) as row_count
FROM audit_log_config;

-- ============================================================================
-- Rollback Instructions
-- ============================================================================
-- To rollback this migration:
-- DROP TABLE IF EXISTS audit_logs;
-- DROP TABLE IF EXISTS audit_log_config;
-- ============================================================================
